const MAX_USER_POKE_COUNT = 2;
const UNLOCK_TIME_TO_POKE = 1000;
const USER_POKE_COUNT = 1;
const TURN_AROUND_CARD = 1000;
const ONE_SECOND = 1;
const ONE_SECOND_IN_MILLISECONDS = 1000;
const ALL_CARDS = 16;

export { ALL_CARDS, ONE_SECOND, ONE_SECOND_IN_MILLISECONDS, MAX_USER_POKE_COUNT, UNLOCK_TIME_TO_POKE, USER_POKE_COUNT, TURN_AROUND_CARD}
